// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2AtmsKJYY4EUZcW2y3wr0Fi_e2lbSLJg',
    appId: '1:470505148516:web:24e263da53aab092688f71',
    messagingSenderId: '470505148516',
    projectId: 'adwaith-49954',
    authDomain: 'adwaith-49954.firebaseapp.com',
    storageBucket: 'adwaith-49954.appspot.com', // ✅ Corrected storage bucket
    databaseURL: 'https://adwaith-49954-default-rtdb.asia-southeast1.firebasedatabase.app', // ✅ Added database URL
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd1NSMYbNxPBeshpQVq4tftBnMXSf_AL8',
    appId: '1:470505148516:android:8c7a53da8f09bcb0688f71',
    messagingSenderId: '470505148516',
    projectId: 'adwaith-49954',
    storageBucket: 'adwaith-49954.appspot.com', // ✅ Corrected storage bucket
    databaseURL: 'https://adwaith-49954-default-rtdb.asia-southeast1.firebasedatabase.app', // ✅ Added database URL
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2AtmsKJYY4EUZcW2y3wr0Fi_e2lbSLJg',
    appId: '1:470505148516:web:bc028c95454322c9688f71',
    messagingSenderId: '470505148516',
    projectId: 'adwaith-49954',
    authDomain: 'adwaith-49954.firebaseapp.com',
    storageBucket: 'adwaith-49954.appspot.com', // ✅ Corrected storage bucket
    databaseURL: 'https://adwaith-49954-default-rtdb.asia-southeast1.firebasedatabase.app', // ✅ Added database URL
  );
}
